/* This file was generated by syncqt. */
#ifndef QT_QTCLUCENE_VERSION_H
#define QT_QTCLUCENE_VERSION_H

#define QTCLUCENE_VERSION_STR "5.6.3"

#define QTCLUCENE_VERSION 0x050603

#endif // QT_QTCLUCENE_VERSION_H
