QT.help_private.VERSION = 5.6.3
QT.help_private.MAJOR_VERSION = 5
QT.help_private.MINOR_VERSION = 6
QT.help_private.PATCH_VERSION = 3
QT.help_private.name = QtHelp
QT.help_private.module =
QT.help_private.libs = $$QT_MODULE_LIB_BASE
QT.help_private.includes = $$QT_MODULE_INCLUDE_BASE/QtHelp/5.6.3 $$QT_MODULE_INCLUDE_BASE/QtHelp/5.6.3/QtHelp
QT.help_private.frameworks =
QT.help_private.depends = core_private help
QT.help_private.module_config = v2 internal_module
